# Generated by Django 4.2.4 on 2023-09-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_terms"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Usuario", "Usuario"), ("Administrador", "Administrador")],
                default="Usuario",
                max_length=100,
            ),
        ),
    ]
