# Generated by Django 4.2.4 on 2024-03-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rfc',
        ),
    ]
