# Generated by Django 4.2.4 on 2024-03-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='starter',
            field=models.BooleanField(default=False),
        ),
    ]
