# Generated by Django 4.2.4 on 2024-04-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_starter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codigo',
            field=models.CharField(default='SV7273', max_length=100, unique=True),
        ),
    ]
