# Generated by Django 4.2.4 on 2024-04-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codigo',
            field=models.CharField(default='MS5OBN', max_length=100),
        ),
    ]
