# Generated by Django 4.2.4 on 2024-04-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='codigo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
