# Generated by Django 4.2.4 on 2023-09-07 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Donaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "evidencia",
                    models.ImageField(blank=True, null=True, upload_to="evidencias"),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Donacion",
                "verbose_name_plural": "Donaciones",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Redes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Red",
                "verbose_name_plural": "Redes",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B")], default="A", max_length=50
                    ),
                ),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiario_suscripcion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "donador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donador_suscripcion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "red",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sistema.redes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripcion",
                "verbose_name_plural": "Suscripciones",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="DonacionRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("comentarios", models.TextField(blank=True, null=True)),
                ("aprobado", models.BooleanField(default=False)),
                ("resolucion", models.TextField(blank=True, null=True)),
                (
                    "donacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sistema.donaciones",
                    ),
                ),
                (
                    "revisor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DonacionRevision",
                "verbose_name_plural": "DonacionRevisiones",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="donaciones",
            name="red",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sistema.redes"
            ),
        ),
    ]
