# Generated by Django 4.2.4 on 2024-03-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_suscripcion_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripcion',
            name='tipo',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2')], default='A', max_length=50),
        ),
    ]
